version: '3'

services:
  employee-audit:
    image: 415579337695.dkr.ecr.us-east-2.amazonaws.com/employee-audit
    labels:
      - "traefik.http.routers.employee-audit.rule=Host(`ea.teraception.com`)"
      - "traefik.http.routers.employee-audit.service=employee-audit"
      - "traefik.http.routers.employee-audit.tls=true"
      - "traefik.http.services.employee-audit.loadbalancer.server.port=3000"
    env_file:
      - .env.prod
    environment:
      - DATABASE_URL=/app/db
    volumes:
      - db:/app/db